### ISSUE TITLE
Precompile not working

### ISSUE THREAD

**Issue by pullmann4rent** [vinejs/vine#29] opened 2024-02-01 21:46 UTC
### Package version

1.7.1

### Describe the bug

I want to precompile vinejs but not working if I precompile or not I got 20ms+ for a simple validation. Other libaries takes 1-3ms. So anything I doing it wrong.

Server.ts
```
import vine from '@vinejs/vine';
const app = express();

export const schemaTenantsAdmin = vine.object({
  email: vine.string().email(),
  password: vine.string().minLength(6).confirmed(),
  firstname: vine.string(),
  lastname: vine.string(),
  city: vine.string(),
  street: vine.string(),
  zipcode: vine.string(),
  category: vine.string(),
  company: vine.string(),
  domain: vine.string(),
  code: vine.number()
});
export const validatorVine = vine.compile(schemaTenantsAdmin);

app.use(morgan('dev'));
app.use(express.urlencoded({extended: true}));

//Reduce Fingerprint
app.disable('x-powered-by');

app.use(helmet());

// app.use(rateLimiter);

app.use('/api/auth', router_auth);

// Custom Error Handler
app.use(errorHandler);

app.listen(3000, () => {
 console.log('SERVER LISTEN ON PORT 3000');
});
```

SignUp.ts
```
export const SignUpTenantsAdmin = async (req: Request, res: Response) => {
  try {
    await validatorVine.validate(req.body);
    
    res.send('x');
  } catch(e) {
    Sentry.captureException(e);
    console.log(e);
    res.status(500).json(e);
  }
};
```

**Comment by RomainLanz** [comment] 2024-02-07 11:05
Hey @pullmann4rent! 👋🏻 

Please give us a repository with minimum application to reproduce the issue. Also, please add another validator so we can ensure your claim.

**Comment by RomainLanz** [comment] 2024-02-12 10:30
Closing since no answer from issue reporter.

**Closed by RomainLanz** 2024-02-12 10:30 UTC
