### ISSUE TITLE
Add rule names to compiled schema

### ISSUE THREAD

**Issue by arthur-er** [vinejs/vine#25] opened 2024-01-26 15:38 UTC
### Package version

1.7.0

### Describe the bug

Opening this as a bug because there's no way to open feature request issues right now.

Add names to rules similar to the `Symbol(schema_nme)` on s, this will allow for tooling like vine to zod/vine to json schema to be more complete feature-wise. Including a `Symbol(rule_name)` in rules would do the trick

**Comment by thetutlage** [comment] 2024-03-28 10:05
Hey, sorry picking up it a bit late. Can you please share some examples of that exactly you need in the compiled output?

**Comment by thetutlage** [comment] 2024-11-29 02:13
Closing since not actionable

**Closed by thetutlage** 2024-11-29 02:13 UTC

**Comment by ivansansao** [comment] 2025-02-18 03:48
Hi team, how are you? 😊  

I'm also trying to **export the schema to the frontend (React)**, where I dynamically convert it to **Yup**. However, I can't find a way to retrieve the **rule names** for each field (e.g., `"string"`, `"trim"`, `"minLength"`, `"maxLength"`, `"email"`, `"optional"`).  

In **Adonis V5**, I was able to extract this information easily, but with VineJS, I've tried everything and still can't get the rule names. Instead, `toJSON()` only provides **`ref://X` identifiers**, which makes it difficult to dynamically map the rules.  

Here’s an example of my schema:  

```ts
const createPostValidator = vine.compile(
  vine.object({
    title: vine.string().trim().minLength(6).maxLength(20),
    email: vine.string().email().optional(),
  })
)

console.log(createPostValidator.toJSON())
```

**Current Output:**
```ts
{
  schema: {
    type: 'root',
    schema: {
      type: 'object',
      properties: [Array],
    }
  },
  refs: {
    'ref://1': { validator: [Function (anonymous)], options: undefined },
    'ref://2': { validator: [Function (anonymous)], options: undefined },
    'ref://3': { validator: [Function (anonymous)], options: { min: 6 } },
    'ref://4': { validator: [Function (anonymous)], options: { max: 20 } },
    'ref://5': { validator: [Function (anonymous)], options: undefined },
    'ref://6': { validator: [Function (anonymous)], options: undefined }
  }
}
```

### **❌ Problem**
- The `toJSON()` output only includes `ref://X` identifiers instead of rule names.
- The validator functions inside `refs` are anonymous, so I can't extract their names.
- This makes it **impossible to dynamically convert VineJS validation to Yup**.

### **💡 Feature Request / Possible Solutions**
Would it be possible to:
1. **Include the rule names directly in `toJSON()`**, alongside the `ref://X` identifiers?
2. Provide a way to retrieve the rule names programmatically, even if it’s through an internal API?
3. Allow setting metadata inside `meta()` so we can attach rule names manually?

### **🔍 Expected Behavior**
I would expect `toJSON()` to provide **human-readable rule names** like:

```ts
refs: {
  'ref://1': { validator: "string", options: undefined },
  'ref://2': { validator: "trim", options: undefined },
  'ref://3': { validator: "minLength", options: { min: 6 } },
  'ref://4': { validator: "maxLength", options: { max: 20 } },
  'ref://5': { validator: "email", options: undefined },
  'ref://6': { validator: "optional", options: undefined }
}
```

Thanks in advance!
